// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using VisitsApp;

namespace VisitsApp
{
    public partial class AzureVisitsApi : ServiceClient<AzureVisitsApi>, IAzureVisitsApi
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IQuickTexts _quickTexts;
        
        public virtual IQuickTexts QuickTexts
        {
            get { return this._quickTexts; }
        }
        
        private IServiceUsers _serviceUsers;
        
        public virtual IServiceUsers ServiceUsers
        {
            get { return this._serviceUsers; }
        }
        
        private IServiceUserTypes _serviceUserTypes;
        
        public virtual IServiceUserTypes ServiceUserTypes
        {
            get { return this._serviceUserTypes; }
        }
        
        private IVisitors _visitors;
        
        public virtual IVisitors Visitors
        {
            get { return this._visitors; }
        }
        
        private IVisits _visits;
        
        public virtual IVisits Visits
        {
            get { return this._visits; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AzureVisitsApi class.
        /// </summary>
        public AzureVisitsApi()
            : base()
        {
            this._quickTexts = new QuickTexts(this);
            this._serviceUsers = new ServiceUsers(this);
            this._serviceUserTypes = new ServiceUserTypes(this);
            this._visitors = new Visitors(this);
            this._visits = new Visits(this);
            this._baseUri = new Uri("http://visitsapi.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the AzureVisitsApi class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public AzureVisitsApi(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._quickTexts = new QuickTexts(this);
            this._serviceUsers = new ServiceUsers(this);
            this._serviceUserTypes = new ServiceUserTypes(this);
            this._visitors = new Visitors(this);
            this._visits = new Visits(this);
            this._baseUri = new Uri("http://visitsapi.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the AzureVisitsApi class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public AzureVisitsApi(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._quickTexts = new QuickTexts(this);
            this._serviceUsers = new ServiceUsers(this);
            this._serviceUserTypes = new ServiceUserTypes(this);
            this._visitors = new Visitors(this);
            this._visits = new Visits(this);
            this._baseUri = new Uri("http://visitsapi.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the AzureVisitsApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public AzureVisitsApi(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the AzureVisitsApi class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public AzureVisitsApi(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the AzureVisitsApi class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public AzureVisitsApi(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
