//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitsApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VisitModelContainer : DbContext
    {
        public VisitModelContainer()
            : base("name=VisitModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ServiceUserType> ServiceUserTypes { get; set; }
        public virtual DbSet<QuickText> QuickTexts { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<ServiceUser> ServiceUsers { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
