// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using VisitsApp.Models;

namespace VisitsApp.Models
{
    public static partial class QuickTextCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<QuickText> DeserializeJson(JToken inputObject)
        {
            IList<QuickText> deserializedObject = new List<QuickText>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                QuickText quickText = new QuickText();
                quickText.DeserializeJson(iListValue);
                deserializedObject.Add(quickText);
            }
            return deserializedObject;
        }
    }
}
