// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using VisitsApp.Models;

namespace VisitsApp.Models
{
    public static partial class ServiceUserTypeCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ServiceUserType> DeserializeJson(JToken inputObject)
        {
            IList<ServiceUserType> deserializedObject = new List<ServiceUserType>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ServiceUserType serviceUserType = new ServiceUserType();
                serviceUserType.DeserializeJson(iListValue);
                deserializedObject.Add(serviceUserType);
            }
            return deserializedObject;
        }
    }
}
