// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using VisitsApp.Models;

namespace VisitsApp.Models
{
    public static partial class ServiceUserCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ServiceUser> DeserializeJson(JToken inputObject)
        {
            IList<ServiceUser> deserializedObject = new List<ServiceUser>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ServiceUser serviceUser = new ServiceUser();
                serviceUser.DeserializeJson(iListValue);
                deserializedObject.Add(serviceUser);
            }
            return deserializedObject;
        }
    }
}
